Remove setting singleModule on compilation args in KotlinCompilation.kt
singleModule was removed from K2JVMCompilerArguments in https://github.com/JetBrains/kotlin/commit/a76de140265a4fdd03fb9c7b642a9cdef7c9c179

Now, setting singleModule will result in a NoSuchMethodError.